name: eye_tracking
description: A Flutter plugin for real-time eye tracking with sub-degree accuracy. Supports web, iOS, and Android platforms with calibration, gaze coordinates, eye state detection, and head pose estimation.
version: 0.1.0
homepage: https://pub.dev/packages/eye_tracking
repository: https://github.com/Piyushhhhh/eye_tracking
issue_tracker: https://github.com/Piyushhhhh/eye_tracking/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - eye-tracking
  - computer-vision
  - webgazer
  - gaze-tracking
  - accessibility

flutter:
  plugin:
    platforms:
      web:
        pluginClass: EyeTrackingWeb
        fileName: eye_tracking_web.dart
      android:
        package: dev.eyetracking.flutter
        pluginClass: EyeTrackingPlugin
      ios:
        pluginClass: EyeTrackingPlugin


